apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-external
spec:
  hosts:
    - httpbin-mutual-tls.jeremysolarz.app
  location: MESH_EXTERNAL
  ports:
    - number: 3306
      name: tcp
      protocol: TCP
    - number: 16443
      name: tls
      protocol: TLS
  resolution: DNS
  endpoints:
    - address: httpbin-mutual-tls.jeremysolarz.app
      ports:
        tls: 16443